<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="MX-IT00121" name="com.automation.training.tests.StarBucksTests" tests="9" failures="1" timestamp="13 Apr 2018 07:38:46 GMT" time="9.546" errors="0">
  <testcase name="testStarBucksHomeDataProvider" time="2.441" classname="com.automation.training.tests.StarBucksTests"/>
  <testcase name="testStarBucksHomeDataProvider" time="1.049" classname="com.automation.training.tests.StarBucksTests"/>
  <testcase name="testStarBucksHomeDataProvider" time="1.008" classname="com.automation.training.tests.StarBucksTests"/>
  <testcase name="testStarBucksHomeDataProvider" time="1.124" classname="com.automation.training.tests.StarBucksTests"/>
  <testcase name="testStarBucksHomeDataProvider" time="1.036" classname="com.automation.training.tests.StarBucksTests"/>
  <testcase name="test2" time="0.000" classname="com.automation.training.tests.StarBucksTests">
    <failure type="org.testng.TestNGException" message="
Method public void com.automation.training.tests.StarBucksTests.test2(java.lang.Object,java.lang.Object,java.lang.Object,java.lang.Object,java.lang.String) throws java.lang.InterruptedException requires a @DataProvider named : Tabdata2">
      <![CDATA[org.testng.TestNGException: 
Method public void com.automation.training.tests.StarBucksTests.test2(java.lang.Object,java.lang.Object,java.lang.Object,java.lang.Object,java.lang.String) throws java.lang.InterruptedException requires a @DataProvider named : Tabdata2
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:265)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:414)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1383)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1075)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1180)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="testStarBucksHomeDataProvider" time="0.715" classname="com.automation.training.tests.StarBucksTests"/>
  <testcase name="testStarBucksHomeDataProvider" time="1.104" classname="com.automation.training.tests.StarBucksTests"/>
  <testcase name="testStarBucksHomeDataProvider" time="1.069" classname="com.automation.training.tests.StarBucksTests"/>
</testsuite> <!-- com.automation.training.tests.StarBucksTests -->
